
Exception Time :   15/1/2020 06:42

Exception Message :   
One or more errors occurred.

Exception InnerException :   
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> 
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

Exception StackTrace :   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 73

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 06:47

Exception Message :   
One or more errors occurred.

Exception InnerException :   
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

Exception StackTrace :   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 79

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 06:52

Exception Message :   
One or more errors occurred.

Exception InnerException :   
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

Exception StackTrace :   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 79

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 06:55

Exception Message :   
One or more errors occurred.

Exception InnerException :   
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

Exception StackTrace :   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 79

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 06:55

Exception Message :   
One or more errors occurred.

Exception InnerException :   
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

Exception StackTrace :   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 79

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 07:33

Exception Message :   
The remote name could not be resolved: 'kuwaitportal.paci.gov.kw'

Exception InnerException :   


Exception StackTrace :   
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at MapIt.Helpers.PresentHelper.GenerateToken() in F:\MapIt\MapItWebsite\MapIt\MapIt.Helpers\PresentHelper.cs:line 405

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 07:34

Exception Message :   
One or more errors occurred.

Exception InnerException :   
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

Exception StackTrace :   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 118

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 07:39

Exception Message :   
One or more errors occurred.

Exception InnerException :   
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

Exception StackTrace :   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 116

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 08:31

Exception Message :   
Object reference not set to an instance of an object.

Exception InnerException :   


Exception StackTrace :   
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 140

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 08:44

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url)
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 145

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 08:53

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url)
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 158

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Exception Time :   15/1/2020 08:57

Exception Message :   
Thread was being aborted.

Exception InnerException :   


Exception StackTrace :   
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponse.Redirect(String url)
   at MapIt.Web.Payment.Buy.SendRequest() in F:\MapIt\MapItWebsite\MapIt\MapIt.Web\Payment\Buy.aspx.cs:line 158

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
